### ISSUE TITLE
Update artwork

### ISSUE THREAD

**Issue by bekverdyan** [pouk/piramida#1]

**Comment by antaranyan** [comment]
[Big Data Outline](https://thenounproject.com/korawan_m/collection/big-data-outline/) collection from the [Noun Project](https://thenounproject.com)

![image](https://user-images.githubusercontent.com/25614707/60374484-c7e25380-9a15-11e9-86ba-22a7a6c9eb5a.png) 
![image](https://user-images.githubusercontent.com/25614707/60374491-d6306f80-9a15-11e9-9849-0bed449f4e13.png) 
![image](https://user-images.githubusercontent.com/25614707/60374514-e9433f80-9a15-11e9-8bf4-684e865624bc.png)

**Comment by bekverdyan** [comment]
https://thenounproject.com/term/pyramid/49084/
![image](https://user-images.githubusercontent.com/49238154/60374875-98344b00-9a17-11e9-94fc-a1c81a8bdf94.png)

Attribution text: 

> Pyramid by stolkramaker from the Noun Project

**Comment by antaranyan** [comment]
[Miscellaneous Icons 1 Collection](https://thenounproject.com/creativestall/collection/miscellaneous-icons-1)

![image](https://user-images.githubusercontent.com/25614707/60374731-f0b71880-9a16-11e9-92a9-fe85b985c971.png) 
![image](https://user-images.githubusercontent.com/25614707/60374775-2956f200-9a17-11e9-89ff-ed6adcc74813.png)
